import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar"
import Footer from "@/components/shared/Footer";
import LeftsideCategoryContainer from "@/components/LeftsideCategoryContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Yasribe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-hidden `}
      >
        <Navbar />

        <div className="flex  scrollbar-hide ">
          <div className="overflow-scroll scrollbar-hide hidden lg:block  w-3/16">
            <LeftsideCategoryContainer></LeftsideCategoryContainer>
          </div>


          <div className="overflow-scroll h-screen scrollbar-hide lg:w-13/16 ">
            {children}
            <Footer />
          </div>

        </div>


      </body>
    </html>
  );
}
